trigger: none
pool:
  vmImage: ubuntu-latest

steps:
- task: AzureCLI@2
  displayName: "Test ARM token"
  inputs:
    azureSubscription: 'mi-pipeline-api'   # サービス接続名
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      echo "=== ARM token ==="
      az account get-access-token --resource https://management.azure.com

      echo "=== Graph token ==="
      az account get-access-token --resource https://graph.microsoft.com
