# azure-pipelines.yml
# Microsoft-hosted Agent (Ubuntu) で動く最小テストパイプライン

trigger:
- main   # main ブランチに push されたら実行

pool:
  vmImage: 'ubuntu-latest'   # Microsoft-hosted Agent を利用

steps:
- script: echo "✅ Hello from Microsoft-hosted Ubuntu Agent!"
  displayName: "Say hello (Ubuntu)"

- script: |
    echo "Agent OS: $(Agent.OS)"
    echo "Agent Name: $(Agent.Name)"
    echo "Agent Version: $(Agent.Version)"
    echo "Job triggered at: $(Build.QueuedTime)"
  displayName: "Show agent info"
