trigger:
- main

variables:
  system.debug: true

jobs:
- job: ubuntu
  displayName: "Ubuntu debug"
  pool: { vmImage: 'ubuntu-latest' }
  steps:
  - checkout: self
  - script: |
      echo "Hello from Ubuntu"
      echo "Agent.OS=$(Agent.OS)"
    displayName: "Hello (Ubuntu)"
  - bash: |
      set -euxo pipefail
      uname -a || true
      cat /etc/os-release || true
      which terraform || true; terraform -version || true
      which az || true; az version || true
    displayName: "Linux debug dump"

- job: windows
  displayName: "Windows debug"
  dependsOn: ubuntu
  pool: { vmImage: 'windows-latest' }
  steps:
  - checkout: self
  - pwsh: |
      Write-Host "Hello from Windows"
      Write-Host "Agent.OS=$(Agent.OS)"
      $PSVersionTable
      systeminfo | findstr /B /C:"OS Name" /C:"OS Version"
      where terraform; terraform -version
      where az; az version
    displayName: "Windows debug dump"
