# azure-pipelines.yml
# Microsoft-hosted (Azure Pipelines) での実行確認用・最小テスト
# 手動実行向けに trigger は無効化（必要なら main に変更）

trigger: none

stages:
- stage: sanity
  displayName: "Run on Microsoft-hosted agents"
  jobs:
  # --- Ubuntu ---
  - job: ubuntu
    displayName: "Ubuntu on Azure Pipelines"
    pool:
      name: 'Azure Pipelines'
      vmImage: 'ubuntu-latest'
    steps:
    - checkout: none
    - script: |
        echo "✅ Hello from Ubuntu (Microsoft-hosted)"
        echo "Agent.Name=$(Agent.Name)"
        echo "Agent.OS=$(Agent.OS)"
        echo "Agent.Version=$(Agent.Version)"
        echo "Image=ubuntu-latest"
        az --version || true
      displayName: "Sanity (Ubuntu)"

  # --- Windows ---
  - job: windows
    displayName: "Windows on Azure Pipelines"
    dependsOn: ubuntu
    pool:
      name: 'Azure Pipelines'
      vmImage: 'windows-latest'
    steps:
    - checkout: none
    - pwsh: |
        Write-Host "✅ Hello from Windows (Microsoft-hosted)"
        Write-Host "Agent.Name=$(Agent.Name)"
        Write-Host "Agent.OS=$(Agent.OS)"
        Write-Host "Agent.Version=$(Agent.Version)"
        Write-Host "Image=windows-latest"
        az --version
      displayName: "Sanity (Windows)"
