trigger: none
pr: none
pool:
  vmImage: 'windows-latest'

stages:
- stage: debug
  jobs:
  - job: probe
    steps:
    - task: AzureCLI@2
      displayName: "WHOAMI / RBAC / Billing roles"
      inputs:
        azureSubscription: 'snp-pipeline-api'   # ←あなたのService connection名
        scriptType: ps
        scriptLocation: inlineScript
        inlineScript: |
          $ErrorActionPreference = 'Stop'

          # WHOAMI
          $acct = az account show --only-show-errors | ConvertFrom-Json
          $clientId = $acct.user.name
          $tenantId = $acct.tenantId
          $sp = az ad sp show --id $clientId --only-show-errors | ConvertFrom-Json
          $spDisp  = $sp.displayName
          $spObjId = $sp.id
          Write-Host "SP Name  : $spDisp"
          Write-Host "ClientId : $clientId"
          Write-Host "ObjectId : $spObjId"
          Write-Host "TenantId : $tenantId"
          Write-Host ""

          # RBAC（参考）
          Write-Host "== Azure RBAC role assignments =="
          az role assignment list --assignee $spObjId --all -o table

          # Billing 拡張
          if (-not (az extension list -o tsv | Select-String -SimpleMatch "billing")) {
            az extension add --name billing --only-show-errors
          }

          $api="2024-04-01"
          Write-Host ""
          Write-Host "== Try list Billing Accounts =="
          try {
            az rest --method get --url "https://management.azure.com/providers/Microsoft.Billing/billingAccounts?api-version=$api"
            Write-Host "[OK] billingAccounts list succeeded (少なくとも参照権はある)"
          } catch {
            Write-Warning "[NG] billingAccounts list failed（Billing ロール不足の可能性が高い）"
            Write-Host $_.Exception.Message
          }
